# Site settings
title: Georgia Tech's AI Blog
email: 
description: "Welcome to GeorgiaTech.AI, where student researchers bring artificial intelligence to life through visual storytelling."
baseurl: ""
url: "https://georgiatech.ai"
youtube_username: gatechai
spotify_username:  gatechai

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
