# Site settings
title: Georgia Tech AI Podcast
email: 
description: "Demystifying cutting-edge AI research from Georgia Tech's top minds, making this knowledge accessible to all."
baseurl: "gatechai"
url: "https://georgiatech.ai"
youtube_username: gatechai
spotify_username:  gatechai

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
